name: Basic Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "GitHub Actions are working!"
