name: Update Submission Status

on:
  pull_request:
    branches:
      - '*'

jobs:
  update_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests PyGithub

      - name: Check GITHUB_TOKEN
        run: echo "MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}"

      - name: Run update script
        run: python update_submission_status.py
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_HEAD_REF: ${{ github.event.pull_request.title }}
          GITHUB_EVENT_PR_CREATED_AT: ${{ github.event.pull_request.created_at }}
